### ISSUE TITLE
Function breaks if working in big range.

### ISSUE THREAD

**Issue by Penultimate-Return** [Penultimate-Return/PrimeNumberSet-Cpp#1]
**When starts from 1 and ends with 10000000  (7 '0' here), **the functions do not hold up till the end**.**

**Comment by Penultimate-Return** [comment]
startFrom:1
endWith: 10000000

এরকম বড় range input দিলে কাজ করে না।

**Comment by RaSan147** [comment]
there was no issue even when running via android.
